package org.mmarini.scalarl.v4.agents

import org.mmarini.scalarl.v4.{Agent, Feedback}
import org.nd4j.linalg.api.ndarray.INDArray

/**
 * The information of a step generated by a learning session
 *
 * @Constructor creates a [Step]
 * @param feedback the feedback
 * @param agent0   the agent
 * @param agent1   the changed agent
 * @param score    the score
 */
case class AgentEvent(feedback: Feedback,
                      agent0: Agent,
                      agent1: Agent,
                      score: INDArray)
