package org.mmarini.scalarl.v4.agents

import org.mmarini.scalarl.v4.{Agent, Feedback}

/**
 * The information of a step generated by a learning session
 *
 * @Constructor creates a [Step]
 * @param feedback the feedback
 * @param agent    the agent
 * @param map      the data map
 * @param map1     the data map
 */
case class AgentEvent(feedback: Feedback,
                      agent: Agent,
                      map: Map[String, Any],
                      map1: Map[String, Any])
